/* Generated by TinyPHP — PHP → C (TCC) */

#include "common.h"

/* ── Struct: Main ──────────────────────────── */
typedef struct {
t_object _base;
} Main;

void Main___construct(Main* self, t_int argc, t_array* argv);
void Main___destruct(Main* self);
void Main_main(Main* self);
Main* new_Main(t_int argc, t_array* argv);

/* ── Struct: Demo ──────────────────────────── */
typedef struct {
t_object _base;
} Demo;

void Demo___construct(Demo* self, t_int argc, t_array* argv);
void Demo___destruct(Demo* self);
void Demo_hello(Demo* self);
Demo* new_Demo(void);

static void tphp_test();
static t_int tphp_test2();
static t_string tphp_test3(t_string str);

/* ── VTable: Main ──────────────────────────── */
static const ClassVTable _vtable_Main = {
    .name    = "Main",
    .type_id = 0,
    .dtor    = (void(*)(void*))Main___destruct,
};

void Main___construct(Main* self, t_int argc, t_array* argv) {
if (self == NULL) return;
(void)argc;
(void)argv;
}

void Main___destruct(Main* self) {
if (self == NULL) return;
}

void Main_main(Main* self) {
if (self == NULL) return;
tphp_echo(STR_LIT("hello world\n"));
tphp_test();
tphp_echo(tphp_str_from_int(tphp_test2()));
Demo* c = new_Demo();
Demo_hello(c);
tphp_object_free(&c->_base);
}

/* ── Allocator: new_Main ──────────────── */
Main* new_Main(t_int argc, t_array* argv) {
Main* self = (Main*)calloc(1, sizeof(Main));
if (self == NULL) return NULL;
self->_base.vtable   = &_vtable_Main;
self->_base.refcount = 1;
Main___construct(self, argc, argv);
return self;
}

/* ── VTable: Demo ──────────────────────────── */
static const ClassVTable _vtable_Demo = {
    .name    = "Demo",
    .type_id = 0,
    .dtor    = (void(*)(void*))Demo___destruct,
};

void Demo___construct(Demo* self, t_int argc, t_array* argv) {
if (self == NULL) return;
tphp_echo(STR_LIT("new Demo\n"));
}

void Demo___destruct(Demo* self) {
if (self == NULL) return;
tphp_echo(STR_LIT("delete Demo\n"));
}

void Demo_hello(Demo* self) {
if (self == NULL) return;
tphp_echo(STR_LIT("hello\n"));
}

/* ── Allocator: new_Demo ──────────────── */
Demo* new_Demo(void) {
Demo* self = (Demo*)calloc(1, sizeof(Demo));
if (self == NULL) return NULL;
self->_base.vtable   = &_vtable_Demo;
self->_base.refcount = 1;
t_int _dummy_argc = 0; t_array* _dummy_argv = NULL;
Demo___construct(self, _dummy_argc, _dummy_argv);
return self;
}

static void tphp_test() {
tphp_echo(STR_LIT("test\n"));
}

static t_int tphp_test2() {
t_int a = 10;
t_int b = 20;
t_int c = (a + b);
return c;
}

static t_string tphp_test3(t_string str) {
t_string a = STR_LIT("hello");
t_string c = STR_LIT("$a $str\n");
return c;
}

/* ── C entry: main() ─────────────────────────── */
int main(int argc, char* argv[]) {
t_array* _argv = tphp_build_argv(argc, argv);
Main* _main = new_Main((t_int)argc, _argv);
if (_main == NULL) { tphp_arr_free(_argv); return 1; }
Main_main(_main);
tphp_object_free(&_main->_base);
tphp_arr_free(_argv);
return 0;
}
