<?php

declare(strict_types=1);

class CodeGenerator implements ASTVisitor
{
    private string $className = '';
    private int $indent = 0;

    /** 变量类型追踪：varName → className（对象）或 C 类型（基础类型） */
    private array $varTypes = [];
    /** 已声明变量集合 */
    private array $declaredVars = [];
    /** 当前作用域内的对象变量名列表（用于自动析构） */
    private array $scopeObjects = [];

    /** 字面量 → C 类型的映射 */
    private static array $litTypeMap = [
        IntLiteralExpr::class    => 't_int',
        FloatLiteralExpr::class  => 't_float',
        StringLiteralExpr::class => 't_string',
        BoolLiteralExpr::class   => 't_bool',
    ];

    private static array $typeMap = [
        'int' => 't_int', 'float' => 't_float', 'string' => 't_string',
        'bool' => 't_bool', 'void' => 'void', 'array' => 't_array*',
    ];

    // ============================================================
    public function generate(ProgramNode $program, string $phpFile, string $outputDir): string
    {
        $this->className = $program->mainClass->name;
        $outPath = $outputDir . '/' . pathinfo($phpFile, PATHINFO_FILENAME) . '.c';
        $code = $program->accept($this);
        file_put_contents($outPath, $code);
        return $outPath;
    }

    // ============================================================
    public function visitProgram(ProgramNode $node): string
    {
        $this->indent = 0;
        $p = [];

        // Header
        $p[] = "/* Generated by TinyPHP — PHP → C (TCC) */";
        $p[] = '';
        $p[] = '#include "common.h"';
        $p[] = '';

        $allClasses = array_merge([$node->mainClass], $node->extraClasses);
        $mainClassName = $node->mainClass->name;

        // ── Phase 1: 所有类的 struct + 前置声明 (保证类型可见) ──
        foreach ($allClasses as $class) {
            $this->className = $class->name;
            $isMain = ($class->name === $mainClassName);
            $p[] = $this->emitClassForward($class, $isMain);
        }

        // 独立函数前置声明
        foreach ($node->functions as $fn) {
            $ret = self::mapType($fn->returnType);
            $params = array_map(fn($p) => $this->visitParam($p), $fn->params);
            $p[] = "static {$ret} tphp_{$fn->name}(" . implode(', ', $params) . ');';
        }
        if ($node->functions) $p[] = '';

        // ── Phase 2: 所有类的方法实现 + allocator ──
        foreach ($allClasses as $class) {
            $this->className = $class->name;
            $isMain = ($class->name === $mainClassName);
            $p[] = $this->emitClassImpl($class, $isMain);
        }

        // 独立函数实现
        foreach ($node->functions as $fn) {
            $p[] = $fn->accept($this);
            $p[] = '';
        }

        // C 入口
        $this->className = $node->mainClass->name;
        $p[] = $this->generateCEntry();

        return implode("\n", $p) . "\n";
    }

    /** Phase 1: struct + 前置声明 */
    private function emitClassForward(ClassNode $class, bool $isMain): string
    {
        $cn = $class->name;
        $ctor = $dtor = null;
        $methods = [];
        foreach ($class->methods as $m) {
            if ($m->name === '__construct') $ctor = $m;
            elseif ($m->name === '__destruct') $dtor = $m;
            else $methods[] = $m;
        }

        $o = [];
        $o[] = "/* ── Struct: {$cn} ──────────────────────────── */";
        $o[] = 'typedef struct {';
        $o[] = $this->ind('t_object _base;');
        $o[] = "} {$cn};";
        $o[] = '';
        $o[] = "void {$cn}___construct({$cn}* self, t_int argc, t_array* argv);";
        $o[] = "void {$cn}___destruct({$cn}* self);";
        foreach ($methods as $m) {
            $o[] = $this->methodDecl($m) . ';';
        }
        if ($isMain) {
            $o[] = "{$cn}* new_{$cn}(t_int argc, t_array* argv);";
        } else {
            $o[] = "{$cn}* new_{$cn}(void);";
        }
        $o[] = '';

        return implode("\n", $o);
    }

    /** Phase 2: VTable + 方法实现 + allocator */
    private function emitClassImpl(ClassNode $class, bool $isMain): string
    {
        $cn = $class->name;
        $ctor = $dtor = null;
        $methods = [];
        foreach ($class->methods as $m) {
            if ($m->name === '__construct') $ctor = $m;
            elseif ($m->name === '__destruct') $dtor = $m;
            else $methods[] = $m;
        }

        $o = [];

        // VTable
        $o[] = "/* ── VTable: {$cn} ──────────────────────────── */";
        $o[] = "static const ClassVTable _vtable_{$cn} = {";
        $o[] = $this->ind("    .name    = \"{$cn}\",");
        $o[] = $this->ind("    .type_id = 0,");
        $o[] = $this->ind("    .dtor    = (void(*)(void*)){$cn}___destruct,");
        $o[] = $this->ind("};");
        $o[] = '';

        // __construct（固定签名）
        $o[] = "void {$cn}___construct({$cn}* self, t_int argc, t_array* argv) {";
        $o[] = $this->ind('if (self == NULL) return;');
        if ($ctor && !empty($ctor->body)) {
            foreach ($ctor->body as $s) $o[] = $this->ind($s->accept($this));
        } else {
            $o[] = $this->ind('(void)argc;');
            $o[] = $this->ind('(void)argv;');
        }
        $o[] = '}';
        $o[] = '';

        // __destruct（固定签名）
        $o[] = "void {$cn}___destruct({$cn}* self) {";
        $o[] = $this->ind('if (self == NULL) return;');
        if ($dtor && !empty($dtor->body)) {
            foreach ($dtor->body as $s) $o[] = $this->ind($s->accept($this));
        }
        $o[] = '}';
        $o[] = '';

        // 用户方法
        foreach ($methods as $m) {
            $o[] = $m->accept($this);
            $o[] = '';
        }

        // Allocator — Main 有参数，辅助类无参数
        $o[] = "/* ── Allocator: new_{$cn} ──────────────── */";
        if ($isMain) {
            $o[] = "{$cn}* new_{$cn}(t_int argc, t_array* argv) {";
        } else {
            $o[] = "{$cn}* new_{$cn}(void) {";
        }
        $o[] = $this->ind("{$cn}* self = ({$cn}*)calloc(1, sizeof({$cn}));");
        $o[] = $this->ind('if (self == NULL) return NULL;');
        $o[] = $this->ind("self->_base.vtable   = &_vtable_{$cn};");
        $o[] = $this->ind("self->_base.refcount = 1;");
        if ($isMain) {
            $o[] = $this->ind("{$cn}___construct(self, argc, argv);");
        } else {
            $o[] = $this->ind("t_int _dummy_argc = 0; t_array* _dummy_argv = NULL;");
            $o[] = $this->ind("{$cn}___construct(self, _dummy_argc, _dummy_argv);");
        }
        $o[] = $this->ind('return self;');
        $o[] = '}';
        $o[] = '';

        return implode("\n", $o);
    }

    // ============================================================
    public function visitClass(ClassNode $node): string { return ''; }

    public function visitFunction(FunctionNode $node): string
    {
        $this->declaredVars = [];
        $this->scopeObjects = [];
        $ret = self::mapType($node->returnType);
        $params = array_map(fn($p) => $this->visitParam($p), $node->params);
        // 参数也标记为已声明
        foreach ($node->params as $p) {
            $this->declaredVars[self::varName($p->name)] = true;
        }
        $lines = [];
        $lines[] = "static {$ret} tphp_{$node->name}(" . implode(', ', $params) . ') {';
        foreach ($node->body as $s) $lines[] = $this->ind($s->accept($this));
        // 自动析构本作用域内的对象变量
        foreach ($this->scopeObjects as $ov) {
            $lines[] = $this->ind("tphp_object_free(&{$ov}->_base);");
        }
        $lines[] = '}';
        return implode("\n", $lines);
    }

    public function visitMethod(MethodNode $node): string
    {
        $this->declaredVars = [];
        $this->scopeObjects = [];
        // self + params are all declared
        $this->declaredVars['self'] = true;
        foreach ($node->params as $p) {
            $this->declaredVars[self::varName($p->name)] = true;
        }
        $lines = [];
        $lines[] = $this->methodImpl($node) . ' {';
        $lines[] = $this->ind('if (self == NULL) return;');
        if (empty($node->body)) {
            foreach ($node->params as $p) $lines[] = $this->ind("(void)" . self::varName($p->name) . ";");
        } else {
            foreach ($node->body as $s) $lines[] = $this->ind($s->accept($this));
        }
        // 自动析构本作用域内的对象变量
        foreach ($this->scopeObjects as $ov) {
            $lines[] = $this->ind("tphp_object_free(&{$ov}->_base);");
        }
        $lines[] = '}';
        return implode("\n", $lines);
    }

    public function visitParam(ParamNode $node): string
    {
        return self::mapType($node->type) . ' ' . self::varName($node->name);
    }

    // ============================================================
    public function visitEchoStmt(EchoStmtNode $node): string
    {
        $parts = [];
        foreach ($node->exprs as $e) {
            $code = $e->accept($this);
            // 如果表达式不是字符串字面量/变量引用，可能需要转换
            if ($e instanceof StringLiteralExpr) {
                $parts[] = "tphp_echo({$code});";
            } elseif ($e instanceof VariableExpr) {
                // 变量：推导类型决定是否需要转换
                $vn = self::varName($e->name);
                $vt = $this->varTypes[$vn] ?? '';
                if ($vt === 't_string' || $vt === 't_int' || $vt === 't_float' || $vt === 't_bool') {
                    $parts[] = $this->echoWrap($vt, $code);
                } else {
                    $parts[] = "tphp_echo({$code});";
                }
            } elseif ($e instanceof CallExpr) {
                // 函数调用：默认当作 echo 的参数，推导返回类型
                $parts[] = $this->echoWrap('t_int', $code); // 默认 int
            } else {
                $parts[] = "tphp_echo({$code});";
            }
        }
        return implode("\n" . $this->indentStr(), $parts);
    }

    private function echoWrap(string $type, string $code): string
    {
        return match ($type) {
            't_string' => "tphp_echo({$code});",
            't_int'    => "tphp_echo(tphp_str_from_int({$code}));",
            't_float'  => "tphp_echo(tphp_str_from_float({$code}));",
            't_bool'   => "tphp_echo(tphp_str_from_bool({$code}));",
            default    => "tphp_echo({$code});",
        };
    }

    public function visitReturnStmt(ReturnStmtNode $node): string
    {
        return $node->expr ? 'return ' . $node->expr->accept($this) . ';' : 'return;';
    }

    public function visitAssignStmt(AssignStmtNode $node): string
    {
        $var = self::varName($node->varName);
        $expr = $node->expr->accept($this);
        $isDeclared = isset($this->declaredVars[$var]);
        $this->declaredVars[$var] = true;

        // new ClassName(...) → ClassName* var = expr; + 记录为对象变量
        if ($node->expr instanceof NewExpr) {
            $this->varTypes[$var] = $node->expr->className;
            $this->scopeObjects[] = $var;
            return "{$node->expr->className}* {$var} = {$expr};";
        }

        // 首次赋值 → 推导类型并声明
        if (!$isDeclared) {
            $cType = $this->inferType($node->expr);
            $this->varTypes[$var] = $cType;
            return "{$cType} {$var} = {$expr};";
        }

        return "{$var} = {$expr};";
    }

    /** 从 AST 表达式推导 C 类型 */
    private function inferType(ExprNode $expr): string
    {
        $class = get_class($expr);
        if (isset(self::$litTypeMap[$class])) {
            return self::$litTypeMap[$class];
        }
        if ($expr instanceof BinaryExpr) {
            return $this->inferType($expr->left); // 取左操作数类型
        }
        if ($expr instanceof VariableExpr) {
            $vn = self::varName($expr->name);
            return $this->varTypes[$vn] ?? 't_int';
        }
        if ($expr instanceof CallExpr) {
            return 't_int'; // 默认函数返回 int，后续可优化
        }
        return 't_int'; // fallback
    }

    public function visitExprStmt(ExprStmtNode $node): string
    {
        return $node->expr->accept($this) . ';';
    }

    // ============================================================
    public function visitStringLiteral(StringLiteralExpr $node): string
    {
        $val = str_replace('"', '\\"', $node->value);
        return "STR_LIT(\"{$val}\")";
    }

    public function visitIntLiteral(IntLiteralExpr $node): string    { return (string)$node->value; }
    public function visitFloatLiteral(FloatLiteralExpr $node): string { return (string)$node->value; }
    public function visitBoolLiteral(BoolLiteralExpr $node): string   { return $node->value ? 'true' : 'false'; }
    public function visitNullLiteral(NullLiteralExpr $node): string   { return 'null'; }

    public function visitVariable(VariableExpr $node): string
    {
        $n = self::varName($node->name);
        return $n === '$this' ? 'self' : $n;
    }

    public function visitBinary(BinaryExpr $node): string
    {
        return '(' . $node->left->accept($this) . ' ' . $node->operator . ' ' . $node->right->accept($this) . ')';
    }

    public function visitCall(CallExpr $node): string
    {
        $args = array_map(fn($a) => $a->accept($this), $node->args);
        if ($node->callee === null) {
            // 独立函数加 tphp_ 前缀，避免与 C 标准库冲突
            return 'tphp_' . $node->name . '(' . implode(', ', $args) . ')';
        }
        $callee = $node->callee->accept($this);
        // 方法调用：self 作为第一个参数
        $allArgs = array_merge([$callee], $args);
        // 类名推导
        if ($callee === 'self') {
            $cn = $this->className;
        } else {
            // 从变量类型追踪中查找
            $cn = $this->varTypes[$callee] ?? $callee;
        }
        return "{$cn}_{$node->name}(" . implode(', ', $allArgs) . ')';
    }

    public function visitCast(CastExpr $node): string
    {
        return '((' . self::mapType($node->castType) . ')(' . $node->expr->accept($this) . '))';
    }

    public function visitNew(NewExpr $node): string
    {
        $args = array_map(fn($a) => $a->accept($this), $node->args);
        // 如果没传参且不是 Main，使用 void 版本
        if (empty($args) && $node->className !== $this->className) {
            return "new_{$node->className}()";
        }
        return "new_{$node->className}(" . implode(', ', $args) . ')';
    }

    // ============================================================
    private function generateCEntry(): string
    {
        return implode("\n", [
            "/* ── C entry: main() ─────────────────────────── */",
            "int main(int argc, char* argv[]) {",
            $this->ind("t_array* _argv = tphp_build_argv(argc, argv);"),
            $this->ind("{$this->className}* _main = new_{$this->className}((t_int)argc, _argv);"),
            $this->ind("if (_main == NULL) { tphp_arr_free(_argv); return 1; }"),
            $this->ind("{$this->className}_main(_main);"),
            $this->ind("tphp_object_free(&_main->_base);"),
            $this->ind("tphp_arr_free(_argv);"),
            $this->ind("return 0;"),
            "}",
        ]);
    }

    // ============================================================
    private function methodDecl(MethodNode $m): string
    {
        $ret = self::mapType($m->returnType);
        $params = array_map(fn($p) => $this->visitParam($p), $m->params);
        return "{$ret} {$this->className}_{$m->name}({$this->className}* self" .
            (empty($params) ? '' : ', ' . implode(', ', $params)) . ')';
    }

    private function methodImpl(MethodNode $m): string { return $this->methodDecl($m); }

    public static function mapType(string $t): string { return self::$typeMap[$t] ?? "{$t}*"; }
    public static function varName(string $v): string { return $v === '$this' ? 'self' : ltrim($v, '$'); }

    private function indentStr(): string { return str_repeat('    ', $this->indent); }
    private function ind(string $l): string { return $this->indentStr() . $l; }
}
